package com.quicinc.chatapp.mcp;

import android.util.Log;

import org.json.JSONArray;
import org.json.JSONObject;

import java.util.Iterator;

/**
 * ToolArgSanitizer: Cleans up tool arguments generated by the 3B LLM
 * before sending them to the MCP server.
 *
 * The 3B model frequently:
 * - Sends null values for optional params (MCP rejects these)
 * - Uses wrong param names ("start"/"end" instead of "coordinates")
 * - Uses wrong types (string instead of boolean)
 * - Makes up values ("driving" for "geometries" when it should be a routing profile)
 *
 * This sanitizer fixes what it can and strips the rest.
 */
public class ToolArgSanitizer {

    private static final String TAG = "ToolArgSanitizer";

    /**
     * Sanitize arguments for a given tool before sending to MCP.
     *
     * @param toolName the MCP tool name
     * @param args the raw arguments from the LLM
     * @param currentLat user's current latitude (from GPS)
     * @param currentLon user's current longitude (from GPS)
     * @return cleaned arguments, or the original if no cleaning needed
     */
    public static JSONObject sanitize(String toolName, JSONObject args,
                                       double currentLat, double currentLon) {
        try {
            // Step 1: Remove null values and empty arrays from ALL tools
            JSONObject cleaned = removeNullsAndEmpties(args);

            // Step 2: Apply tool-specific fixes
            String nameLower = toolName.toLowerCase();
            if (nameLower.contains("direction")) {
                cleaned = fixDirectionsArgs(cleaned, currentLat, currentLon);
            } else if (nameLower.contains("search") || nameLower.contains("poi")
                       || nameLower.contains("category")) {
                cleaned = fixSearchArgs(cleaned, currentLat, currentLon);
            } else if (nameLower.contains("geocode_forward") || nameLower.contains("search_geocode")) {
                cleaned = fixGeocodeArgs(cleaned);
            } else if (nameLower.contains("static_map") || nameLower.contains("map_image")) {
                cleaned = fixMapArgs(cleaned, currentLat, currentLon);
            }

            Log.e("toolcalling", "Sanitized args for " + toolName + ": " + cleaned.toString());
            return cleaned;
        } catch (Exception e) {
            Log.w(TAG, "Sanitize failed, using original args: " + e.getMessage());
            return args;
        }
    }

    /**
     * Remove null values, empty arrays, and empty strings from JSON.
     */
    private static JSONObject removeNullsAndEmpties(JSONObject args) throws Exception {
        JSONObject cleaned = new JSONObject();
        Iterator<String> keys = args.keys();
        while (keys.hasNext()) {
            String key = keys.next();
            Object value = args.get(key);

            // Skip null
            if (args.isNull(key)) continue;

            // Skip empty strings
            if (value instanceof String && ((String) value).isEmpty()) continue;

            // Skip empty arrays
            if (value instanceof JSONArray && ((JSONArray) value).length() == 0) continue;

            // Skip zero values for optional numeric params
            if (value instanceof Number) {
                double num = ((Number) value).doubleValue();
                // Keep 0 only for longitude/latitude (valid values)
                if (num == 0 && !key.contains("lon") && !key.contains("lat")
                    && !key.contains("longitude") && !key.contains("latitude")) {
                    continue;
                }
            }

            cleaned.put(key, value);
        }
        return cleaned;
    }

    /**
     * Fix directions_tool arguments.
     * The LLM often sends "start"/"end" strings instead of "coordinates" array.
     */
    private static JSONObject fixDirectionsArgs(JSONObject args, double lat, double lon)
            throws Exception {
        JSONObject fixed = new JSONObject();

        // Build coordinates array from what the LLM gave us
        // directions_tool expects: coordinates = [[lon1,lat1],[lon2,lat2]]
        if (!args.has("coordinates")) {
            // Use current GPS as origin
            JSONArray coordinates = new JSONArray();
            JSONArray origin = new JSONArray();
            origin.put(lon);  // longitude first (GeoJSON convention)
            origin.put(lat);
            coordinates.put(origin);

            // If LLM provided "end" or "destination", we can't geocode here,
            // but we'll at least set origin correctly
            // For now, add a second point offset slightly (MCP will at least not error on format)
            if (args.has("end") || args.has("destination")) {
                // We'll pass the text to MCP and let it error more gracefully,
                // OR we set a reasonable default
                // For now, just duplicate origin — the real fix is to geocode first
                JSONArray dest = new JSONArray();
                dest.put(lon + 0.01);  // Slight offset as placeholder
                dest.put(lat + 0.01);
                coordinates.put(dest);
            }

            fixed.put("coordinates", coordinates);
        } else {
            fixed.put("coordinates", args.get("coordinates"));
        }

        // Set routing profile — the LLM often puts "driving" in "geometries"
        String profile = "driving";
        if (args.has("routing_profile")) {
            profile = args.getString("routing_profile");
        } else if (args.has("geometries") && isRoutingProfile(args.getString("geometries"))) {
            profile = args.getString("geometries");
        } else if (args.has("profile")) {
            profile = args.getString("profile");
        }
        fixed.put("routing_profile", profile);

        // Only include valid optional params
        if (args.has("geometries") && !isRoutingProfile(args.optString("geometries"))) {
            String geom = args.getString("geometries");
            if (geom.equals("geojson") || geom.equals("none")) {
                fixed.put("geometries", geom);
            }
        }

        if (args.has("alternatives")) {
            Object alt = args.get("alternatives");
            if (alt instanceof Boolean) {
                fixed.put("alternatives", alt);
            }
            // If it's a string like "false", convert
            else if (alt instanceof String) {
                fixed.put("alternatives", Boolean.parseBoolean((String) alt));
            }
        }

        return fixed;
    }

    /**
     * Fix search/POI tool arguments.
     * Ensure longitude/latitude are present from GPS.
     */
    private static JSONObject fixSearchArgs(JSONObject args, double lat, double lon)
            throws Exception {
        JSONObject fixed = new JSONObject();

        // Copy query
        if (args.has("query")) {
            fixed.put("query", args.getString("query"));
        } else if (args.has("search") || args.has("name") || args.has("q")) {
            // LLM might use different param names
            String query = args.optString("search",
                args.optString("name", args.optString("q", "")));
            fixed.put("query", query);
        }

        // Ensure coordinates — use GPS if LLM didn't provide
        if (args.has("longitude")) {
            fixed.put("longitude", args.getDouble("longitude"));
        } else if (args.has("lon")) {
            fixed.put("longitude", args.getDouble("lon"));
        } else {
            fixed.put("longitude", lon);
        }

        if (args.has("latitude")) {
            fixed.put("latitude", args.getDouble("latitude"));
        } else if (args.has("lat")) {
            fixed.put("latitude", args.getDouble("lat"));
        } else {
            fixed.put("latitude", lat);
        }

        // Copy limit if present
        if (args.has("limit")) {
            fixed.put("limit", args.getInt("limit"));
        }

        return fixed;
    }

    /**
     * Fix geocode arguments.
     */
    private static JSONObject fixGeocodeArgs(JSONObject args) throws Exception {
        JSONObject fixed = new JSONObject();

        if (args.has("query")) {
            fixed.put("query", args.getString("query"));
        } else if (args.has("address") || args.has("search") || args.has("q")) {
            String query = args.optString("address",
                args.optString("search", args.optString("q", "")));
            fixed.put("query", query);
        }

        return fixed;
    }

    /**
     * Fix static map image arguments.
     */
    private static JSONObject fixMapArgs(JSONObject args, double lat, double lon) throws Exception {
        JSONObject fixed = new JSONObject();

        // Center coordinates
        fixed.put("center_lon", args.has("center_lon") ? args.getDouble("center_lon") : lon);
        fixed.put("center_lat", args.has("center_lat") ? args.getDouble("center_lat") : lat);
        fixed.put("zoom", args.has("zoom") ? args.getInt("zoom") : 14);

        // Copy markers if present
        if (args.has("markers")) {
            fixed.put("markers", args.get("markers"));
        }

        return fixed;
    }

    private static boolean isRoutingProfile(String value) {
        return value != null && (value.equals("driving") || value.equals("walking")
            || value.equals("cycling") || value.equals("driving-traffic"));
    }
}
